"""empty message

Revision ID: 4e7445db238d
Revises: f06e7cd187bd
Create Date: 2020-07-11 21:23:36.094998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7445db238d'
down_revision = 'f06e7cd187bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('age', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
