"""empty message

Revision ID: ce8798141073
Revises: 2edb7505c4a0
Create Date: 2020-07-06 16:39:02.708565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8798141073'
down_revision = '2edb7505c4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('venue_id2', sa.Integer(), nullable=False))
    op.drop_constraint('shows_parent_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_parent_id2_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id2'], ['id'])
    op.create_foreign_key(None, 'shows', 'artists', ['artist_id'], ['id'])
    op.drop_column('shows', 'parent_id')
    op.drop_column('shows', 'parent_id2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('parent_id2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_parent_id2_fkey', 'shows', 'venues', ['parent_id2'], ['id'])
    op.create_foreign_key('shows_parent_id_fkey', 'shows', 'artists', ['parent_id'], ['id'])
    op.drop_column('shows', 'venue_id2')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###
