"""empty message

Revision ID: e2be0d92ea8d
Revises: ca151bd515b9
Create Date: 2020-07-06 17:38:08.974684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2be0d92ea8d'
down_revision = 'ca151bd515b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ArtistVenue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArtistVenue',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ArtistVenue_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='ArtistVenue_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='ArtistVenue_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ArtistVenue_pkey')
    )
    # ### end Alembic commands ###
