"""empty message

Revision ID: f06e7cd187bd
Revises: 7adfcccffbcd
Create Date: 2020-07-11 21:22:24.269543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06e7cd187bd'
down_revision = '7adfcccffbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('age', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'age')
    # ### end Alembic commands ###
