"""empty message

Revision ID: f9bce5c43af5
Revises: e2be0d92ea8d
Create Date: 2020-07-06 17:51:24.671258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bce5c43af5'
down_revision = 'e2be0d92ea8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('shows_venue_id2_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    op.drop_column('shows', 'venue_id2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_venue_id2_fkey', 'shows', 'venues', ['venue_id2'], ['id'])
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
