"""empty message

Revision ID: fb64e1ce9191
Revises: 00f3a874d62b
Create Date: 2020-07-09 11:43:36.215602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb64e1ce9191'
down_revision = '00f3a874d62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue_name')
    # ### end Alembic commands ###
